name: jaspr_bloc
description: A Jaspr implementation of the bloc state management library.
version: 1.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  bloc: ^9.2.0
  jaspr: ^0.23.0

dev_dependencies:
  bloc_lint: ^0.4.1
  jaspr_lints: ^0.7.0
  jaspr_test: ^0.23.0
  lints: ^6.1.0
  test: ^1.31.0
